services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres_network
    depends_on:
      - db

  be:
    image: nmf-be-api:v1.0
    container_name: nmf-api
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8081:8080"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - postgres_network
    depends_on:
      - db

volumes:
  postgres_data:
  
networks:
  postgres_network:
    driver: bridge
